[
    # these two audio dicts will occur one after the other
    dict(
        filename="media/audio1.mp3",
        fadein=5,
        majorticks=[
            0,
            6.3,
            12.3,
            18.3,
            24.3,
            30.3,
            36.3,
            42.3,
            48.3,
            54.3,
            60.3,
            66.3,
            72.3,
            78.3,
            84.3,
            90.3,
            96.3,
            102.3,
        ],
        minorticks=[
            0,
            3.3,
            9.3,
            15.3,
            21.3,
            27.3,
            33.3,
            39.3,
            45.3,
            51.3,
            57.3,
            63.3,
            69.3,
            75.3,
            81.3,
            87.3,
            93.3,
            99.3,
            105.3,
        ],
    ),
    # this video will be muted
    dict(filename="media/hockey.mp4", start=0, end=10, fadein=5, volume=0, trim="none"),
    # the text will occur on top of the video (important that text comes after video)
    [
        dict(
            filename="media/lacy.mp4",
            start=0,
            end=10,
            fadeout=1.2,
            crossfadein=2,
            padding=-2,
        ),
        dict(
            text="hello world",
            color="red",
            fontsize=40,
            duration=8,
            position=("center", "center"),
            fadein=5,
        ),
    ],
    dict(filename="media/hockey.mp4", start=100, end=115),
    dict(filename="media/hockey.mp4", start=0, end=20),
    dict(filename="media/lacy.mp4", start=10, end=30, trim="symmetric"),
    dict(filename="media/lacy.mp4", start=30, end=41, trim="end"),
    dict(filename="media/hockey.mp4", start=5, end=45),
    dict(
        filename="media/lacy.mp4",
        start=0,
        end=5,
        trim="none",
        # crossfadein=2,
        # padding=-2,
    ),
    [
        dict(
            filename="media/photo.png",
            duration=5,
            fadeout=5,
            position=("center", "center"),
            crossfadein=2,
            padding=-2,
        ),
        dict(
            text="goodbye",
            duration=5,
            fadeout=5,
            position=("center", "center"),
            color="purple",
            fontsize=50,
        ),
    ],
]
